variables:
- name: BuildParameters.solution
  value: '**\*.sln'

name: v$(Major).$(Minor).$(Patch)

trigger:
- main

pool:
  vmImage: windows-latest

steps:
  - task: DotNetCoreCLI@2
    displayName: "Build Solution"
    inputs:
      command: 'build'
      projects: $(BuildParameters.solution)
      configuration: $(BuildConfiguration)
      arguments: /p:AssemblyVersion=1.2.3.4
  # - task: GitHubRelease@1
  #   displayName: "Publish Relase To GitHub"
  #   inputs:
  #     gitHubConnection: 'GitHub PAT'
  #     repositoryName: '$(Build.Repository.Name)'
  #     action: 'create'
  #     target: '$(Build.SourceVersion)'
  #     tagSource: 'userSpecifiedTag'
  #     tag: '$(Build.BuildNumber)'
  #     title: '$(Build.BuildNumber) - $(BuildConfiguration) - $(Build.SourceBranchName)'
  #     changeLogCompareToRelease: 'lastFullRelease'
  #     changeLogType: 'commitBased'