variables:
- name: BuildParameters.project
  value: '**\RfmOtaClient.csproj'
- name: TestProject
  value: '**/*UnitTests.csproj'

name: v$(Major).$(Minor).$(Patch)

trigger:
- main

pool:
  vmImage: windows-latest

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '$(BuildParameters.project)'
  # - task: GitHubRelease@1
  #   displayName: "Publish Relase To GitHub"
  #   inputs:
  #     gitHubConnection: 'GitHub PAT'
  #     repositoryName: '$(Build.Repository.Name)'
  #     action: 'create'
  #     target: '$(Build.SourceVersion)'
  #     tagSource: 'userSpecifiedTag'
  #     tag: '$(Build.BuildNumber)'
  #     title: '$(Build.BuildNumber) - $(BuildConfiguration) - $(Build.SourceBranchName)'
  #     changeLogCompareToRelease: 'lastFullRelease'
  #     changeLogType: 'commitBased'
